title: " "
email: " "
description: >-
  https://jekyllrb.com/resources/, Google search meta and site description feed.xml.
baseurl: "" # site subpath such as /blog
url: "https://cambridge-ceu.github.io/"
github_username:  cambridge-ceu
# twitter_username: jekyllrb

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
