title: " "
email: " "
description: >-
  Software/documents created at the CEU linking topics which cover but are not limited to the multi-omics analysis.
baseurl: ""
url: "https://cambridge-ceu.github.io/"
github_username:  cambridge-ceu
twitter_username: clin_hr

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark

header_pages:
  - about.md
  - index.md
  - external.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
