title: " "
email: " "
description: >-
  Software/documents developed at the CEU linking topics such as multi-omics analysis
baseurl: ""
url: "https://cambridge-ceu.github.io/"
github_username:  cambridge-ceu
twitter_username: clinical_hr

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives

minima:
  skin: dark

jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

header_pages:
  - index.md
  - external.md
  - about.md
  - archive.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
